name: Deploy to K3s Cluster

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v1

      # Step 2: Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          mv ./kubectl /usr/local/bin/kubectl

      # Step 3: Set up Kubeconfig from GitHub Secrets
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Step 4: Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      # Step 5: Debug kubectl deployments and pods
      - name: Debug kubectl get deployments and pods
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl describe deployments
          kubectl describe pods

